import { DiceType, _roll } from "../DiceRoll";

export enum MonsterType {
  Acolyte = "Acolyte", Archmage = "Archmage", Assassin = "Assassin", Bandit = "Bandit", BanditCaptain = "Bandit Captain", Berserker = "Berserker", Commoner = "Commoner", Cultist = "Cultist", CultFanatic = "Cult Fanatic", Druid = "Druid", Gladiator = "Gladiator", Guard = "Guard", Knight = "Knight", Mage = "Mage", Noble = "Noble", Priest = "Priest", Scout = "Scout", Spy = "Spy", Thug = "Thug", TribalWarrior = "Tribal Warrior", Veteran = "Veteran", Aboleth = "Aboleth", AdultBlackDragon = "Adult Black Dragon", AdultBlueDragon = "Adult Blue Dragon", AdultBrassDragon = "Adult Brass Dragon", AdultBronzeDragon = "Adult Bronze Dragon", AdultCopperDragon = "Adult Copper Dragon", AdultGoldDragon = "Adult Gold Dragon", AdultGreenDragon = "Adult Green Dragon", AdultRedDragon = "Adult Red Dragon", AdultSilverDragon = "Adult Silver Dragon", AdultWhiteDragon = "Adult White Dragon", AirElemental = "Air Elemental", Allosaurus = "Allosaurus", AncientBlackDragon = "Ancient Black Dragon", AncientBlueDragon = "Ancient Blue Dragon", AncientBrassDragon = "Ancient Brass Dragon", AncientBronzeDragon = "Ancient Bronze Dragon", AncientCopperDragon = "Ancient Copper Dragon", AncientGoldDragon = "Ancient Gold Dragon", AncientGreenDragon = "Ancient Green Dragon", AncientRedDragon = "Ancient Red Dragon", AncientSilverDragon = "Ancient Silver Dragon", AncientWhiteDragon = "Ancient White Dragon", Androsphinx = "Androsphinx", AnimatedArmor = "Animated Armor", Ankheg = "Ankheg", Ankylosaurus = "Ankylosaurus", Ape = "Ape", AwakenedShrub = "Awakened Shrub", AwakenedTree = "Awakened Tree", AxeBeak = "Axe Beak", Azer = "Azer", Baboon = "Baboon", Badger = "Badger", Balor = "Balor", BarbedDevil = "Barbed Devil", Banshee = "Banshee", Basilisk = "Basilisk", Bat = "Bat", BeardedDevil = "Bearded Devil", Behir = "Behir", BlackBear = "Black Bear", BlackDragonWyrmling = "Black Dragon Wyrmling", BlackPudding = "Black Pudding", BlinkDog = "Blink Dog", BloodHawk = "Blood Hawk", BlueDragonWyrmling = "Blue Dragon Wyrmling", Boar = "Boar", BoneDevil = "Bone Devil", BrassDragonWyrmling = "Brass Dragon Wyrmling", BronzeDragonWyrmling = "Bronze Dragon Wyrmling", BrownBear = "Brown Bear", Bugbear = "Bugbear", Bulette = "Bulette", Camel = "Camel", Cat = "Cat", Centaur = "Centaur", ChainDevil = "Chain Devil", Chimera = "Chimera", Chuul = "Chuul", ClayGolem = "Clay Golem", Cloaker = "Cloaker", CloudGiant = "Cloud Giant", Cockatrice = "Cockatrice", ConstrictorSnake = "Constrictor Snake", CopperDragonWyrmling = "Copper Dragon Wyrmling", Couatl = "Couatl", Crab = "Crab", Crocodile = "Crocodile", Cyclops = "Cyclops", Darkmantle = "Darkmantle", DeathDog = "Death Dog", Deer = "Deer", DeepGnomeSvirfneblin = "Deep Gnome (Svirfneblin)", Deva = "Deva", Djinni = "Djinni", DireWolf = "Dire Wolf", Doppelganger = "Doppelganger", DraftHorse = "Draft Horse", DragonTurtle = "Dragon Turtle", Dretch = "Dretch", Drider = "Drider", Drow = "Drow", Dryad = "Dryad", Duergar = "Duergar", DustMephit = "Dust Mephit", Eagle = "Eagle", EarthElemental = "Earth Elemental", Efreeti = "Efreeti", Elephant = "Elephant", Elk = "Elk", Erinyes = "Erinyes", Ettercap = "Ettercap", Ettin = "Ettin", FireElemental = "Fire Elemental", FireGiant = "Fire Giant", Flameskull = "Flameskull", FleshGolem = "Flesh Golem", FlyingSnake = "Flying Snake", FlyingSword = "Flying Sword", Frog = "Frog", FrostGiant = "Frost Giant", Gargoyle = "Gargoyle", GelatinousCube = "Gelatinous Cube", Ghast = "Ghast", Ghost = "Ghost", Ghoul = "Ghoul", GiantApe = "Giant Ape", GiantBadger = "Giant Badger", GiantBat = "Giant Bat", GiantBoar = "Giant Boar", GiantCentipede = "Giant Centipede", GiantConstrictorSnake = "Giant Constrictor Snake", GiantCrab = "Giant Crab", GiantCrocodile = "Giant Crocodile", GiantEagle = "Giant Eagle", GiantElk = "Giant Elk", GiantFireBeetle = "Giant Fire Beetle", GiantFrog = "Giant Frog", GiantGoat = "Giant Goat", GiantHyena = "Giant Hyena", GiantLizard = "Giant Lizard", GiantOctopus = "Giant Octopus", GiantOwl = "Giant Owl", GiantPoisonousSnake = "Giant Poisonous Snake", GiantRat = "Giant Rat", GiantScorpion = "Giant Scorpion", GiantSeaHorse = "Giant Sea Horse", GiantShark = "Giant Shark", GiantSpider = "Giant Spider", GiantToad = "Giant Toad", GiantVulture = "Giant Vulture", GiantWasp = "Giant Wasp", GiantWeasel = "Giant Weasel", GiantWolfSpider = "Giant Wolf Spider", Glabrezu = "Glabrezu", GibberingMouther = "Gibbering Mouther", Gnoll = "Gnoll", Goat = "Goat", Goblin = "Goblin", GoldDragonWyrmling = "Gold Dragon Wyrmling", Gorgon = "Gorgon", GrayOoze = "Gray Ooze", GreenDragonWyrmling = "Green Dragon Wyrmling", GreenHag = "Green Hag", Grick = "Grick", Griffon = "Griffon", Grimlock = "Grimlock", GuardianNaga = "Guardian Naga", Gynosphinx = "Gynosphinx", HalfRedDragonVeteran = "Half-Red Dragon Veteran", Harpy = "Harpy", Hawk = "Hawk", HellHound = "Hell Hound", Hezrou = "Hezrou", HillGiant = "Hill Giant", Hippogriff = "Hippogriff", Hobgoblin = "Hobgoblin", Homunculus = "Homunculus", HornedDevil = "Horned Devil", HunterShark = "Hunter Shark", Hydra = "Hydra", Hyena = "Hyena", IceDevil = "Ice Devil", IceMephit = "Ice Mephit", Imp = "Imp", InvisibleStalker = "Invisible Stalker", IronGolem = "Iron Golem", Jackal = "Jackal", KillerWhale = "Killer Whale", Kobold = "Kobold", Kraken = "Kraken", Lamia = "Lamia", Lemure = "Lemure", Lich = "Lich", Lion = "Lion", Lizard = "Lizard", Lizardfolk = "Lizardfolk", MagmaMephit = "Magma Mephit", Magmin = "Magmin", Mammoth = "Mammoth", Manticore = "Manticore", Marilith = "Marilith", Mastiff = "Mastiff", Medusa = "Medusa", Merfolk = "Merfolk", Merrow = "Merrow", Mimic = "Mimic", Minotaur = "Minotaur", MinotaurSkeleton = "Minotaur Skeleton", Mule = "Mule", Mummy = "Mummy", MummyLord = "Mummy Lord", Nalfeshnee = "Nalfeshnee", Nightmare = "Nightmare", NightHag = "Night Hag", Nothic = "Nothic", OchreJelly = "Ochre Jelly", Octopus = "Octopus", Ogre = "Ogre", OgreZombie = "Ogre Zombie", Oni = "Oni", Orc = "Orc", Otyugh = "Otyugh", Owl = "Owl", Owlbear = "Owlbear", Panther = "Panther", Pegasus = "Pegasus", PhaseSpider = "Phase Spider", PitFiend = "Pit Fiend", Planetar = "Planetar", Plesiosaurus = "Plesiosaurus", PoisonousSnake = "Poisonous Snake", PolarBear = "Polar Bear", Pony = "Pony", Pseudodragon = "Pseudodragon", Pteranodon = "Pteranodon", PurpleWorm = "Purple Worm", Quasit = "Quasit", Quipper = "Quipper", Rakshasa = "Rakshasa", Rat = "Rat", Raven = "Raven", RedDragonWyrmling = "Red Dragon Wyrmling", ReefShark = "Reef Shark", Remorhaz = "Remorhaz", Rhinoceros = "Rhinoceros", RidingHorse = "Riding Horse", Roc = "Roc", Roper = "Roper", RugofSmothering = "Rug of Smothering", RustMonster = "Rust Monster", SaberToothedTiger = "Saber-Toothed Tiger", Sahuagin = "Sahuagin", Salamander = "Salamander", Satyr = "Satyr", Scorpion = "Scorpion", SeaHag = "Sea Hag", SeaHorse = "Sea Horse", Shadow = "Shadow", ShamblingMound = "Shambling Mound", ShieldGuardian = "Shield Guardian", Shrieker = "Shrieker", SilverDragonWyrmling = "Silver Dragon Wyrmling", Skeleton = "Skeleton", Solar = "Solar", Spectator = "Spectator", Specter = "Specter", Spider = "Spider", SpiritNaga = "Spirit Naga", Sprite = "Sprite", SteamMephit = "Steam Mephit", Stirge = "Stirge", StoneGiant = "Stone Giant", StoneGolem = "Stone Golem", StormGiant = "Storm Giant", Succubus = "Succubus/Incubus", SwarmofBats = "Swarm of Bats", SwarmofInsects = "Swarm of Insects", SwarmofPoisonousSnakes = "Swarm of Poisonous Snakes", SwarmofQuippers = "Swarm of Quippers", SwarmofRats = "Swarm of Rats", SwarmofRavens = "Swarm of Ravens", Tarrasque = "Tarrasque", Tiger = "Tiger", Treant = "Treant", Triceratops = "Triceratops", Troll = "Troll", TwigBlight = "Twig Blight", TyrannosaurusRex = "Tyrannosaurus Rex", Unicorn = "Unicorn", Vampire = "Vampire", VampireSpawn = "Vampire Spawn", VioletFungus = "Violet Fungus", Vrock = "Vrock", Vulture = "Vulture", Warhorse = "Warhorse", WarhorseSkeleton = "Warhorse Skeleton", WaterElemental = "Water Elemental", Weasel = "Weasel", Werebear = "Werebear", Wereboar = "Wereboar", Wererat = "Wererat", Weretiger = "Weretiger", Werewolf = "Werewolf", WhiteDragonWyrmling = "White Dragon Wyrmling", Wight = "Wight", WillOWisp = "Will-o’-Wisp", WinterWolf = "Winter Wolf", Wolf = "Wolf", Worg = "Worg", Wraith = "Wraith", Wyvern = "Wyvern", Xorn = "Xorn", Zombie = "Zombie", Wereraven = "Wereraven", NeeddleBlight = "Needdle Blight", Revenant = "Revenant", Scarecrow = "Scarecrow", StrahdZombie = "Strahd's Zombie", EsmereldadAvenir = "Esmerelda d’Avenir", Rahadin = "Rahadin", BroomofAnimatedAttack = "Broom of Animated Attack", CrawlingClaw = "Crawling Claw", BarovianWitch = "Barovian Witch", Strahd = "Strahd"
}

export interface IMonsterData {
  type: string;
  hpRoll?: () => number;
  hpModifier?: number;
  challenge?: string;
  reference: string;
  hp?: number;
  name?: string;
  xp?: number
}

export const monsterData: IMonsterData[] = [
  { xp: 50, type: "Acolyte", hpRoll: _roll(2, DiceType.d8), hpModifier: 0, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Acolyte" },
  { xp: 8400, type: "Archmage", hpRoll: _roll(18, DiceType.d8), hpModifier: 18, challenge: "12", reference: "https://www.dndbeyond.com/monsters/Archmage" },
  { xp: 3900, type: "Assassin", hpRoll: _roll(12, DiceType.d8), hpModifier: 24, challenge: "8", reference: "https://www.dndbeyond.com/monsters/Assassin" },
  { xp: 25, type: "Bandit", hpRoll: _roll(2, DiceType.d8), hpModifier: 2, challenge: "1/8", reference: "https://www.dndbeyond.com/monsters/Bandit" },
  { xp: 450, type: "Bandit Captain", hpRoll: _roll(10, DiceType.d8), hpModifier: 20, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Bandit-Captain" },
  { xp: 450, type: "Berserker", hpRoll: _roll(9, DiceType.d8), hpModifier: 27, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Berserker" },
  { xp: 10, type: "Commoner", hpRoll: _roll(1, DiceType.d8), hpModifier: 0, challenge: "0", reference: "https://www.dndbeyond.com/monsters/Commoner" },
  { xp: 25, type: "Cultist", hpRoll: _roll(2, DiceType.d8), hpModifier: 0, challenge: "1/8", reference: "https://www.dndbeyond.com/monsters/Cultist" },
  { xp: 450, type: "Cult Fanatic", hpRoll: _roll(6, DiceType.d8), hpModifier: 6, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Cult-Fanatic" },
  { xp: 450, type: "Druid", hpRoll: _roll(5, DiceType.d8), hpModifier: 5, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Druid" },
  { xp: 1800, type: "Gladiator", hpRoll: _roll(15, DiceType.d8), hpModifier: 45, challenge: "5", reference: "https://www.dndbeyond.com/monsters/Gladiator" },
  { xp: 25, type: "Guard", hpRoll: _roll(2, DiceType.d8), hpModifier: 2, challenge: "1/8", reference: "https://www.dndbeyond.com/monsters/Guard" },
  { xp: 700, type: "Knight", hpRoll: _roll(8, DiceType.d8), hpModifier: 16, challenge: "3", reference: "https://www.dndbeyond.com/monsters/Knight" },
  { xp: 2300, type: "Mage", hpRoll: _roll(9, DiceType.d8), hpModifier: 0, challenge: "6", reference: "https://www.dndbeyond.com/monsters/Mage" },
  { xp: 25, type: "Noble", hpRoll: _roll(2, DiceType.d8), hpModifier: 0, challenge: "1/8", reference: "https://www.dndbeyond.com/monsters/Noble" },
  { xp: 450, type: "Priest", hpRoll: _roll(5, DiceType.d8), hpModifier: 5, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Priest" },
  { xp: 100, type: "Scout", hpRoll: _roll(3, DiceType.d8), hpModifier: 3, challenge: "1/2", reference: "https://www.dndbeyond.com/monsters/Scout" },
  { xp: 200, type: "Spy", hpRoll: _roll(6, DiceType.d8), hpModifier: 0, challenge: "1", reference: "https://www.dndbeyond.com/monsters/Spy" },
  { xp: 100, type: "Thug", hpRoll: _roll(5, DiceType.d8), hpModifier: 10, challenge: "1/2", reference: "https://www.dndbeyond.com/monsters/Thug" },
  { xp: 25, type: "Tribal Warrior", hpRoll: _roll(2, DiceType.d8), hpModifier: 2, challenge: "1/8", reference: "https://www.dndbeyond.com/monsters/Tribal-Warrior" },
  { xp: 700, type: "Veteran", hpRoll: _roll(9, DiceType.d8), hpModifier: 18, challenge: "3", reference: "https://www.dndbeyond.com/monsters/Veteran" },
  { xp: 5900, type: "Aboleth", hpRoll: _roll(18, DiceType.d10), hpModifier: 36, challenge: "10", reference: "https://www.dndbeyond.com/monsters/Aboleth" },
  { xp: 11500, type: "Adult Black Dragon", hpRoll: _roll(17, DiceType.d12), hpModifier: 85, challenge: "14", reference: "https://www.dndbeyond.com/monsters/Adult-Black-Dragon" },
  { xp: 15000, type: "Adult Blue Dragon", hpRoll: _roll(18, DiceType.d12), hpModifier: 108, challenge: "16", reference: "https://www.dndbeyond.com/monsters/Adult-Blue-Dragon" },
  { xp: 10000, type: "Adult Brass Dragon", hpRoll: _roll(15, DiceType.d12), hpModifier: 75, challenge: "13", reference: "https://www.dndbeyond.com/monsters/Adult-Brass-Dragon" },
  { xp: 13000, type: "Adult Bronze Dragon", hpRoll: _roll(17, DiceType.d12), hpModifier: 102, challenge: "15", reference: "https://www.dndbeyond.com/monsters/Adult-Bronze-Dragon" },
  { xp: 11500, type: "Adult Copper Dragon", hpRoll: _roll(16, DiceType.d12), hpModifier: 80, challenge: "14", reference: "https://www.dndbeyond.com/monsters/Adult-Copper-Dragon" },
  { xp: 18000, type: "Adult Gold Dragon", hpRoll: _roll(19, DiceType.d12), hpModifier: 133, challenge: "17", reference: "https://www.dndbeyond.com/monsters/Adult-Gold-Dragon" },
  { xp: 13000, type: "Adult Green Dragon", hpRoll: _roll(18, DiceType.d12), hpModifier: 90, challenge: "15", reference: "https://www.dndbeyond.com/monsters/Adult-Green-Dragon" },
  { xp: 18000, type: "Adult Red Dragon", hpRoll: _roll(19, DiceType.d12), hpModifier: 133, challenge: "17", reference: "https://www.dndbeyond.com/monsters/Adult-Red-Dragon" },
  { xp: 15000, type: "Adult Silver Dragon", hpRoll: _roll(18, DiceType.d12), hpModifier: 126, challenge: "16", reference: "https://www.dndbeyond.com/monsters/Adult-Silver-Dragon" },
  { xp: 10000, type: "Adult White Dragon", hpRoll: _roll(16, DiceType.d12), hpModifier: 96, challenge: "13", reference: "https://www.dndbeyond.com/monsters/Adult-White-Dragon" },
  { xp: 1800, type: "Air Elemental", hpRoll: _roll(12, DiceType.d10), hpModifier: 24, challenge: "5", reference: "https://www.dndbeyond.com/monsters/Air-Elemental" },
  { xp: 450, type: "Allosaurus", hpRoll: _roll(6, DiceType.d10), hpModifier: 18, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Allosaurus" },
  { xp: 33000, type: "Ancient Black Dragon", hpRoll: _roll(21, DiceType.d20), hpModifier: 147, challenge: "21", reference: "https://www.dndbeyond.com/monsters/Ancient-Black-Dragon" },
  { xp: 50000, type: "Ancient Blue Dragon", hpRoll: _roll(26, DiceType.d20), hpModifier: 208, challenge: "23", reference: "https://www.dndbeyond.com/monsters/Ancient-Blue-Dragon" },
  { xp: 25000, type: "Ancient Brass Dragon", hpRoll: _roll(17, DiceType.d20), hpModifier: 119, challenge: "20", reference: "https://www.dndbeyond.com/monsters/Ancient-Brass-Dragon" },
  { xp: 41000, type: "Ancient Bronze Dragon", hpRoll: _roll(24, DiceType.d20), hpModifier: 192, challenge: "22", reference: "https://www.dndbeyond.com/monsters/Ancient-Bronze-Dragon" },
  { xp: 33000, type: "Ancient Copper Dragon", hpRoll: _roll(20, DiceType.d20), hpModifier: 140, challenge: "21", reference: "https://www.dndbeyond.com/monsters/Ancient-Copper-Dragon" },
  { xp: 62000, type: "Ancient Gold Dragon", hpRoll: _roll(28, DiceType.d20), hpModifier: 252, challenge: "24", reference: "https://www.dndbeyond.com/monsters/Ancient-Gold-Dragon" },
  { xp: 41000, type: "Ancient Green Dragon", hpRoll: _roll(22, DiceType.d20), hpModifier: 154, challenge: "22", reference: "https://www.dndbeyond.com/monsters/Ancient-Green-Dragon" },
  { xp: 62000, type: "Ancient Red Dragon", hpRoll: _roll(28, DiceType.d20), hpModifier: 252, challenge: "24", reference: "https://www.dndbeyond.com/monsters/Ancient-Red-Dragon" },
  { xp: 50000, type: "Ancient Silver Dragon", hpRoll: _roll(25, DiceType.d20), hpModifier: 225, challenge: "23", reference: "https://www.dndbeyond.com/monsters/Ancient-Silver-Dragon" },
  { xp: 25000, type: "Ancient White Dragon", hpRoll: _roll(18, DiceType.d20), hpModifier: 144, challenge: "20", reference: "https://www.dndbeyond.com/monsters/Ancient-White-Dragon" },
  { xp: 18000, type: "Androsphinx", hpRoll: _roll(19, DiceType.d10), hpModifier: 95, challenge: "17", reference: "https://www.dndbeyond.com/monsters/Androsphinx" },
  { xp: 200, type: "Animated Armor", hpRoll: _roll(6, DiceType.d8), hpModifier: 6, challenge: "1", reference: "https://www.dndbeyond.com/monsters/Animated-Armor" },
  { xp: 450, type: "Ankheg", hpRoll: _roll(6, DiceType.d10), hpModifier: 6, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Ankheg" },
  { xp: 700, type: "Ankylosaurus", hpRoll: _roll(8, DiceType.d12), hpModifier: 16, challenge: "3", reference: "https://www.dndbeyond.com/monsters/Ankylosaurus" },
  { xp: 100, type: "Ape", hpRoll: _roll(3, DiceType.d8), hpModifier: 6, challenge: "1/2", reference: "https://www.dndbeyond.com/monsters/Ape" },
  { xp: 10, type: "Awakened Shrub", hpRoll: _roll(3, DiceType.d6), hpModifier: 0, challenge: "0", reference: "https://www.dndbeyond.com/monsters/Awakened-Shrub" },
  { xp: 450, type: "Awakened Tree", hpRoll: _roll(7, DiceType.d12), hpModifier: 14, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Awakened-Tree" },
  { xp: 50, type: "Axe Beak", hpRoll: _roll(3, DiceType.d10), hpModifier: 3, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Axe-Beak" },
  { xp: 450, type: "Azer", hpRoll: _roll(6, DiceType.d8), hpModifier: 12, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Azer" },
  { xp: 10, type: "Baboon", hpRoll: _roll(1, DiceType.d6), hpModifier: 0, challenge: "0", reference: "https://www.dndbeyond.com/monsters/Baboon" },
  { xp: 10, type: "Badger", hpRoll: _roll(1, DiceType.d4), hpModifier: 1, challenge: "0", reference: "https://www.dndbeyond.com/monsters/Badger" },
  { xp: 22000, type: "Balor", hpRoll: _roll(21, DiceType.d12), hpModifier: 126, challenge: "19", reference: "https://www.dndbeyond.com/monsters/Balor" },
  { xp: 1800, type: "Barbed Devil", hpRoll: _roll(13, DiceType.d8), hpModifier: 52, challenge: "5", reference: "https://www.dndbeyond.com/monsters/Barbed-Devil" },
  { xp: 1100, type: "Banshee", hpRoll: _roll(13, DiceType.d8), hpModifier: 0, challenge: "4", reference: "https://www.dndbeyond.com/monsters/Banshee" },
  { xp: 700, type: "Basilisk", hpRoll: _roll(8, DiceType.d8), hpModifier: 16, challenge: "3", reference: "https://www.dndbeyond.com/monsters/Basilisk" },
  { xp: 10, type: "Bat", hpRoll: _roll(1, DiceType.d4), hpModifier: 0, challenge: "0", reference: "https://www.dndbeyond.com/monsters/Bat" },
  { xp: 700, type: "Bearded Devil", hpRoll: _roll(8, DiceType.d8), hpModifier: 16, challenge: "3", reference: "https://www.dndbeyond.com/monsters/Bearded-Devil" },
  { xp: 7200, type: "Behir", hpRoll: _roll(16, DiceType.d12), hpModifier: 64, challenge: "11", reference: "https://www.dndbeyond.com/monsters/Behir" },
  { xp: 100, type: "Black Bear", hpRoll: _roll(3, DiceType.d8), hpModifier: 6, challenge: "1/2", reference: "https://www.dndbeyond.com/monsters/Black-Bear" },
  { xp: 450, type: "Black Dragon Wyrmling", hpRoll: _roll(6, DiceType.d8), hpModifier: 6, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Black-Dragon-Wyrmling" },
  { xp: 1100, type: "Black Pudding", hpRoll: _roll(10, DiceType.d10), hpModifier: 30, challenge: "4", reference: "https://www.dndbeyond.com/monsters/Black-Pudding" },
  { xp: 50, type: "Blink Dog", hpRoll: _roll(4, DiceType.d8), hpModifier: 4, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Blink-Dog" },
  { xp: 25, type: "Blood Hawk", hpRoll: _roll(2, DiceType.d6), hpModifier: 0, challenge: "1/8", reference: "https://www.dndbeyond.com/monsters/Blood-Hawk" },
  { xp: 700, type: "Blue Dragon Wyrmling", hpRoll: _roll(8, DiceType.d8), hpModifier: 16, challenge: "3", reference: "https://www.dndbeyond.com/monsters/Blue-Dragon-Wyrmling" },
  { xp: 50, type: "Boar", hpRoll: _roll(2, DiceType.d8), hpModifier: 2, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Boar" },
  { xp: 5000, type: "Bone Devil", hpRoll: _roll(15, DiceType.d10), hpModifier: 60, challenge: "9", reference: "https://www.dndbeyond.com/monsters/Bone-Devil" },
  { xp: 200, type: "Brass Dragon Wyrmling", hpRoll: _roll(3, DiceType.d8), hpModifier: 3, challenge: "1", reference: "https://www.dndbeyond.com/monsters/Brass-Dragon-Wyrmling" },
  { xp: 450, type: "Bronze Dragon Wyrmling", hpRoll: _roll(5, DiceType.d8), hpModifier: 10, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Bronze-Dragon-Wyrmling" },
  { xp: 200, type: "Brown Bear", hpRoll: _roll(4, DiceType.d10), hpModifier: 12, challenge: "1", reference: "https://www.dndbeyond.com/monsters/Brown-Bear" },
  { xp: 200, type: "Bugbear", hpRoll: _roll(5, DiceType.d8), hpModifier: 5, challenge: "1", reference: "https://www.dndbeyond.com/monsters/Bugbear" },
  { xp: 1800, type: "Bulette", hpRoll: _roll(9, DiceType.d10), hpModifier: 45, challenge: "5", reference: "https://www.dndbeyond.com/monsters/Bulette" },
  { xp: 25, type: "Camel", hpRoll: _roll(2, DiceType.d10), hpModifier: 4, challenge: "1/8", reference: "https://www.dndbeyond.com/monsters/Camel" },
  { xp: 10, type: "Cat", hpRoll: _roll(1, DiceType.d4), hpModifier: 0, challenge: "0", reference: "https://www.dndbeyond.com/monsters/Cat" },
  { xp: 450, type: "Centaur", hpRoll: _roll(6, DiceType.d10), hpModifier: 12, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Centaur" },
  { xp: 3900, type: "Chain Devil", hpRoll: _roll(10, DiceType.d8), hpModifier: 40, challenge: "8", reference: "https://www.dndbeyond.com/monsters/Chain-Devil" },
  { xp: 2300, type: "Chimera", hpRoll: _roll(12, DiceType.d10), hpModifier: 48, challenge: "6", reference: "https://www.dndbeyond.com/monsters/Chimera" },
  { xp: 1100, type: "Chuul", hpRoll: _roll(11, DiceType.d10), hpModifier: 33, challenge: "4", reference: "https://www.dndbeyond.com/monsters/Chuul" },
  { xp: 5000, type: "Clay Golem", hpRoll: _roll(14, DiceType.d10), hpModifier: 56, challenge: "9", reference: "https://www.dndbeyond.com/monsters/Clay-Golem" },
  { xp: 3900, type: "Cloaker", hpRoll: _roll(12, DiceType.d10), hpModifier: 12, challenge: "8", reference: "https://www.dndbeyond.com/monsters/Cloaker" },
  { xp: 5000, type: "Cloud Giant", hpRoll: _roll(16, DiceType.d12), hpModifier: 96, challenge: "9", reference: "https://www.dndbeyond.com/monsters/Cloud-Giant" },
  { xp: 100, type: "Cockatrice", hpRoll: _roll(6, DiceType.d6), hpModifier: 6, challenge: "1/2", reference: "https://www.dndbeyond.com/monsters/Cockatrice" },
  { xp: 50, type: "Constrictor Snake", hpRoll: _roll(2, DiceType.d10), hpModifier: 2, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Constrictor-Snake" },
  { xp: 200, type: "Copper Dragon Wyrmling", hpRoll: _roll(4, DiceType.d8), hpModifier: 4, challenge: "1", reference: "https://www.dndbeyond.com/monsters/Copper-Dragon-Wyrmling" },
  { xp: 1100, type: "Couatl", hpRoll: _roll(13, DiceType.d8), hpModifier: 39, challenge: "4", reference: "https://www.dndbeyond.com/monsters/Couatl" },
  { xp: 10, type: "Crab", hpRoll: _roll(1, DiceType.d4), hpModifier: 0, challenge: "0", reference: "https://www.dndbeyond.com/monsters/Crab" },
  { xp: 100, type: "Crocodile", hpRoll: _roll(3, DiceType.d10), hpModifier: 3, challenge: "1/2", reference: "https://www.dndbeyond.com/monsters/Crocodile" },
  { xp: 2300, type: "Cyclops", hpRoll: _roll(12, DiceType.d12), hpModifier: 60, challenge: "6", reference: "https://www.dndbeyond.com/monsters/Cyclops" },
  { xp: 100, type: "Darkmantle", hpRoll: _roll(5, DiceType.d6), hpModifier: 5, challenge: "1/2", reference: "https://www.dndbeyond.com/monsters/Darkmantle" },
  { xp: 200, type: "Death Dog", hpRoll: _roll(6, DiceType.d8), hpModifier: 12, challenge: "1", reference: "https://www.dndbeyond.com/monsters/Death-Dog" },
  { xp: 10, type: "Deer", hpRoll: _roll(1, DiceType.d8), hpModifier: 0, challenge: "0", reference: "https://www.dndbeyond.com/monsters/Deer" },
  { xp: 100, type: "Deep Gnome (Svirfneblin)", hpRoll: _roll(3, DiceType.d6), hpModifier: 6, challenge: "", reference: "https://www.dndbeyond.com/monsters/Deep-Gnome-Svirfneblin" },
  { xp: 5900, type: "Deva", hpRoll: _roll(16, DiceType.d8), hpModifier: 64, challenge: "10", reference: "https://www.dndbeyond.com/monsters/Deva" },
  { xp: 7200, type: "Djinni", hpRoll: _roll(14, DiceType.d10), hpModifier: 84, challenge: "11", reference: "https://www.dndbeyond.com/monsters/Djinni" },
  { xp: 200, type: "Dire Wolf", hpRoll: _roll(5, DiceType.d10), hpModifier: 10, challenge: "1", reference: "https://www.dndbeyond.com/monsters/Dire-Wolf" },
  { xp: 700, type: "Doppelganger", hpRoll: _roll(8, DiceType.d8), hpModifier: 16, challenge: "3", reference: "https://www.dndbeyond.com/monsters/Doppelganger" },
  { xp: 50, type: "Draft Horse", hpRoll: _roll(3, DiceType.d10), hpModifier: 3, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Draft-Horse" },
  { xp: 18000, type: "Dragon Turtle", hpRoll: _roll(22, DiceType.d20), hpModifier: 110, challenge: "17", reference: "https://www.dndbeyond.com/monsters/Dragon-Turtle" },
  { xp: 50, type: "Dretch", hpRoll: _roll(4, DiceType.d6), hpModifier: 4, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Dretch" },
  { xp: 2300, type: "Drider", hpRoll: _roll(13, DiceType.d10), hpModifier: 52, challenge: "6", reference: "https://www.dndbeyond.com/monsters/Drider" },
  { xp: 50, type: "Drow", hpRoll: _roll(3, DiceType.d8), hpModifier: 0, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Drow" },
  { xp: 200, type: "Dryad", hpRoll: _roll(5, DiceType.d8), hpModifier: 0, challenge: "1", reference: "https://www.dndbeyond.com/monsters/Dryad" },
  { xp: 200, type: "Duergar", hpRoll: _roll(4, DiceType.d8), hpModifier: 8, challenge: "1", reference: "https://www.dndbeyond.com/monsters/Duergar" },
  { xp: 100, type: "Dust Mephit", hpRoll: _roll(5, DiceType.d6), hpModifier: 0, challenge: "1/2", reference: "https://www.dndbeyond.com/monsters/Dust-Mephit" },
  { xp: 10, type: "Eagle", hpRoll: _roll(1, DiceType.d6), hpModifier: 0, challenge: "0", reference: "https://www.dndbeyond.com/monsters/Eagle" },
  { xp: 1800, type: "Earth Elemental", hpRoll: _roll(12, DiceType.d10), hpModifier: 60, challenge: "5", reference: "https://www.dndbeyond.com/monsters/Earth-Elemental" },
  { xp: 7200, type: "Efreeti", hpRoll: _roll(16, DiceType.d10), hpModifier: 112, challenge: "11", reference: "https://www.dndbeyond.com/monsters/Efreeti" },
  { xp: 50, type: "Elephant", hpRoll: _roll(8, DiceType.d12), hpModifier: 24, challenge: "4", reference: "https://www.dndbeyond.com/monsters/Elephant" },
  { xp: 1100, type: "Elk", hpRoll: _roll(2, DiceType.d10), hpModifier: 2, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Elk" },
  { xp: 8400, type: "Erinyes", hpRoll: _roll(18, DiceType.d8), hpModifier: 72, challenge: "12", reference: "https://www.dndbeyond.com/monsters/Erinyes" },
  { xp: 1100, type: "Ettercap", hpRoll: _roll(8, DiceType.d8), hpModifier: 8, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Ettercap" },
  { xp: 450, type: "Ettin", hpRoll: _roll(10, DiceType.d10), hpModifier: 30, challenge: "4", reference: "https://www.dndbeyond.com/monsters/Ettin" },
  { xp: 1800, type: "Fire Elemental", hpRoll: _roll(12, DiceType.d10), hpModifier: 36, challenge: "5", reference: "https://www.dndbeyond.com/monsters/Fire-Elemental" },
  { xp: 5000, type: "Fire Giant", hpRoll: _roll(13, DiceType.d12), hpModifier: 78, challenge: "9", reference: "https://www.dndbeyond.com/monsters/Fire-Giant" },
  { xp: 1800, type: "Flameskull", hpRoll: _roll(9, DiceType.d4), hpModifier: 18, challenge: "4", reference: "https://www.dndbeyond.com/monsters/Flameskull" },
  { xp: 1100, type: "Flesh Golem", hpRoll: _roll(11, DiceType.d8), hpModifier: 44, challenge: "5", reference: "https://www.dndbeyond.com/monsters/Flesh-Golem" },
  { xp: 25, type: "Flying Snake", hpRoll: _roll(2, DiceType.d4), hpModifier: 0, challenge: "1/8", reference: "https://www.dndbeyond.com/monsters/Flying-Snake" },
  { xp: 50, type: "Flying Sword", hpRoll: _roll(5, DiceType.d6), hpModifier: 0, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Flying-Sword" },
  { xp: 10, type: "Frog", hpRoll: _roll(1, DiceType.d4), hpModifier: 0, challenge: "0", reference: "https://www.dndbeyond.com/monsters/Frog" },
  { xp: 3900, type: "Frost Giant", hpRoll: _roll(12, DiceType.d12), hpModifier: 60, challenge: "8", reference: "https://www.dndbeyond.com/monsters/Frost-Giant" },
  { xp: 450, type: "Gargoyle", hpRoll: _roll(7, DiceType.d8), hpModifier: 21, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Gargoyle" },
  { xp: 450, type: "Gelatinous Cube", hpRoll: _roll(8, DiceType.d10), hpModifier: 40, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Gelatinous-Cube" },
  { xp: 450, type: "Ghast", hpRoll: _roll(8, DiceType.d8), hpModifier: 0, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Ghast" },
  { xp: 200, type: "Ghost", hpRoll: _roll(10, DiceType.d8), hpModifier: 0, challenge: "4", reference: "https://www.dndbeyond.com/monsters/Ghost" },
  { xp: 1100, type: "Ghoul", hpRoll: _roll(5, DiceType.d8), hpModifier: 0, challenge: "1", reference: "https://www.dndbeyond.com/monsters/Ghoul" },
  { xp: 2900, type: "Giant Ape", hpRoll: _roll(15, DiceType.d12), hpModifier: 60, challenge: "7", reference: "https://www.dndbeyond.com/monsters/Giant-Ape" },
  { xp: 50, type: "Giant Badger", hpRoll: _roll(2, DiceType.d8), hpModifier: 4, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Giant-Badger" },
  { xp: 450, type: "Giant Bat", hpRoll: _roll(4, DiceType.d10), hpModifier: 0, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Giant-Bat" },
  { xp: 50, type: "Giant Boar", hpRoll: _roll(5, DiceType.d10), hpModifier: 15, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Giant-Boar" },
  { xp: 50, type: "Giant Centipede", hpRoll: _roll(1, DiceType.d6), hpModifier: 1, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Giant-Centipede" },
  { xp: 450, type: "Giant Constrictor Snake", hpRoll: _roll(8, DiceType.d12), hpModifier: 8, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Giant-Constrictor-Snake" },
  { xp: 25, type: "Giant Crab", hpRoll: _roll(3, DiceType.d8), hpModifier: 0, challenge: "1/8", reference: "https://www.dndbeyond.com/monsters/Giant-Crab" },
  { xp: 1800, type: "Giant Crocodile", hpRoll: _roll(9, DiceType.d12), hpModifier: 27, challenge: "5", reference: "https://www.dndbeyond.com/monsters/Giant-Crocodile" },
  { xp: 200, type: "Giant Eagle", hpRoll: _roll(4, DiceType.d10), hpModifier: 4, challenge: "1", reference: "https://www.dndbeyond.com/monsters/Giant-Eagle" },
  { xp: 450, type: "Giant Elk", hpRoll: _roll(5, DiceType.d12), hpModifier: 10, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Giant-Elk" },
  { xp: 10, type: "Giant Fire Beetle", hpRoll: _roll(1, DiceType.d6), hpModifier: 1, challenge: "0", reference: "https://www.dndbeyond.com/monsters/Giant-Fire-Beetle" },
  { xp: 50, type: "Giant Frog", hpRoll: _roll(4, DiceType.d8), hpModifier: 0, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Giant-Frog" },
  { xp: 100, type: "Giant Goat", hpRoll: _roll(3, DiceType.d10), hpModifier: 3, challenge: "1/2", reference: "https://www.dndbeyond.com/monsters/Giant-Goat" },
  { xp: 200, type: "Giant Hyena", hpRoll: _roll(6, DiceType.d10), hpModifier: 12, challenge: "1", reference: "https://www.dndbeyond.com/monsters/Giant-Hyena" },
  { xp: 50, type: "Giant Lizard", hpRoll: _roll(3, DiceType.d10), hpModifier: 3, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Giant-Lizard" },
  { xp: 200, type: "Giant Octopus", hpRoll: _roll(8, DiceType.d10), hpModifier: 8, challenge: "1", reference: "https://www.dndbeyond.com/monsters/Giant-Octopus" },
  { xp: 50, type: "Giant Owl", hpRoll: _roll(3, DiceType.d10), hpModifier: 3, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Giant-Owl" },
  { xp: 50, type: "Giant Poisonous Snake", hpRoll: _roll(2, DiceType.d8), hpModifier: 2, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Giant-Poisonous-Snake" },
  { xp: 25, type: "Giant Rat", hpRoll: _roll(2, DiceType.d6), hpModifier: 0, challenge: "1/8", reference: "https://www.dndbeyond.com/monsters/Giant-Rat" },
  { xp: 700, type: "Giant Scorpion", hpRoll: _roll(7, DiceType.d10), hpModifier: 14, challenge: "3", reference: "https://www.dndbeyond.com/monsters/Giant-Scorpion" },
  { xp: 100, type: "Giant Sea Horse", hpRoll: _roll(3, DiceType.d10), hpModifier: 0, challenge: "1/2", reference: "https://www.dndbeyond.com/monsters/Giant-Sea-Horse" },
  { xp: 1800, type: "Giant Shark", hpRoll: _roll(11, DiceType.d12), hpModifier: 55, challenge: "5", reference: "https://www.dndbeyond.com/monsters/Giant-Shark" },
  { xp: 200, type: "Giant Spider", hpRoll: _roll(4, DiceType.d10), hpModifier: 4, challenge: "1", reference: "https://www.dndbeyond.com/monsters/Giant-Spider" },
  { xp: 200, type: "Giant Toad", hpRoll: _roll(6, DiceType.d10), hpModifier: 6, challenge: "1", reference: "https://www.dndbeyond.com/monsters/Giant-Toad" },
  { xp: 200, type: "Giant Vulture", hpRoll: _roll(3, DiceType.d10), hpModifier: 6, challenge: "1", reference: "https://www.dndbeyond.com/monsters/Giant-Vulture" },
  { xp: 100, type: "Giant Wasp", hpRoll: _roll(3, DiceType.d8), hpModifier: 0, challenge: "1/2", reference: "https://www.dndbeyond.com/monsters/Giant-Wasp" },
  { xp: 25, type: "Giant Weasel", hpRoll: _roll(2, DiceType.d8), hpModifier: 0, challenge: "1/8", reference: "https://www.dndbeyond.com/monsters/Giant-Weasel" },
  { xp: 50, type: "Giant Wolf Spider", hpRoll: _roll(2, DiceType.d8), hpModifier: 2, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Giant-Wolf-Spider" },
  { xp: 5000, type: "Glabrezu", hpRoll: _roll(15, DiceType.d10), hpModifier: 75, challenge: "9", reference: "https://www.dndbeyond.com/monsters/Glabrezu" },
  { xp: 100, type: "Gibbering Mouther", hpRoll: _roll(9, DiceType.d8), hpModifier: 27, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Gibbering-Mouther" },
  { xp: 450, type: "Gnoll", hpRoll: _roll(5, DiceType.d8), hpModifier: 0, challenge: "1/2", reference: "https://www.dndbeyond.com/monsters/Gnoll" },
  { xp: 10, type: "Goat", hpRoll: _roll(1, DiceType.d8), hpModifier: 0, challenge: "0", reference: "https://www.dndbeyond.com/monsters/Goat" },
  { xp: 50, type: "Goblin", hpRoll: _roll(2, DiceType.d6), hpModifier: 0, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Goblin" },
  { xp: 700, type: "Gold Dragon Wyrmling", hpRoll: _roll(8, DiceType.d8), hpModifier: 24, challenge: "3", reference: "https://www.dndbeyond.com/monsters/Gold-Dragon-Wyrmling" },
  { xp: 1800, type: "Gorgon", hpRoll: _roll(12, DiceType.d10), hpModifier: 48, challenge: "5", reference: "https://www.dndbeyond.com/monsters/Gorgon" },
  { xp: 100, type: "Gray Ooze", hpRoll: _roll(3, DiceType.d8), hpModifier: 9, challenge: "1/2", reference: "https://www.dndbeyond.com/monsters/Gray-Ooze" },
  { xp: 450, type: "Green Dragon Wyrmling", hpRoll: _roll(7, DiceType.d8), hpModifier: 7, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Green-Dragon-Wyrmling" },
  { xp: 700, type: "Green Hag", hpRoll: _roll(11, DiceType.d8), hpModifier: 33, challenge: "3", reference: "https://www.dndbeyond.com/monsters/Green-Hag" },
  { xp: 450, type: "Grick", hpRoll: _roll(6, DiceType.d8), hpModifier: 0, challenge: "", reference: "https://www.dndbeyond.com/monsters/Grick" },
  { xp: 450, type: "Griffon", hpRoll: _roll(7, DiceType.d10), hpModifier: 21, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Griffon" },
  { xp: 50, type: "Grimlock", hpRoll: _roll(2, DiceType.d8), hpModifier: 2, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Grimlock" },
  { xp: 5900, type: "Guardian Naga", hpRoll: _roll(15, DiceType.d10), hpModifier: 45, challenge: "10", reference: "https://www.dndbeyond.com/monsters/Guardian-Naga" },
  { xp: 7200, type: "Gynosphinx", hpRoll: _roll(16, DiceType.d10), hpModifier: 48, challenge: "11", reference: "https://www.dndbeyond.com/monsters/Gynosphinx" },
  { xp: 1800, type: "Half-Red Dragon Veteran", hpRoll: _roll(10, DiceType.d8), hpModifier: 20, challenge: "5", reference: "https://www.dndbeyond.com/monsters/Half-Red-Dragon-Veteran" },
  { xp: 200, type: "Harpy", hpRoll: _roll(7, DiceType.d8), hpModifier: 7, challenge: "1", reference: "https://www.dndbeyond.com/monsters/Harpy" },
  { xp: 10, type: "Hawk", hpRoll: _roll(1, DiceType.d4), hpModifier: 0, challenge: "0", reference: "https://www.dndbeyond.com/monsters/Hawk" },
  { xp: 700, type: "Hell Hound", hpRoll: _roll(7, DiceType.d8), hpModifier: 14, challenge: "3", reference: "https://www.dndbeyond.com/monsters/Hell-Hound" },
  { xp: 3900, type: "Hezrou", hpRoll: _roll(13, DiceType.d10), hpModifier: 65, challenge: "8", reference: "https://www.dndbeyond.com/monsters/Hezrou" },
  { xp: 1800, type: "Hill Giant", hpRoll: _roll(10, DiceType.d12), hpModifier: 40, challenge: "5", reference: "https://www.dndbeyond.com/monsters/Hill-Giant" },
  { xp: 200, type: "Hippogriff", hpRoll: _roll(3, DiceType.d10), hpModifier: 3, challenge: "1", reference: "https://www.dndbeyond.com/monsters/Hippogriff" },
  { xp: 100, type: "Hobgoblin", hpRoll: _roll(2, DiceType.d8), hpModifier: 2, challenge: "1/2", reference: "https://www.dndbeyond.com/monsters/Hobgoblin" },
  { xp: 10, type: "Homunculus", hpRoll: _roll(2, DiceType.d4), hpModifier: 0, challenge: "0", reference: "https://www.dndbeyond.com/monsters/Homunculus" },
  { xp: 7200, type: "Horned Devil", hpRoll: _roll(17, DiceType.d10), hpModifier: 85, challenge: "11", reference: "https://www.dndbeyond.com/monsters/Horned-Devil" },
  { xp: 450, type: "Hunter Shark", hpRoll: _roll(6, DiceType.d10), hpModifier: 12, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Hunter-Shark" },
  { xp: 3900, type: "Hydra", hpRoll: _roll(15, DiceType.d12), hpModifier: 75, challenge: "8", reference: "https://www.dndbeyond.com/monsters/Hydra" },
  { xp: 10, type: "Hyena", hpRoll: _roll(1, DiceType.d8), hpModifier: 1, challenge: "0", reference: "https://www.dndbeyond.com/monsters/Hyena" },
  { xp: 11500, type: "Ice Devil", hpRoll: _roll(19, DiceType.d10), hpModifier: 76, challenge: "14", reference: "https://www.dndbeyond.com/monsters/Ice-Devil" },
  { xp: 100, type: "Ice Mephit", hpRoll: _roll(6, DiceType.d6), hpModifier: 0, challenge: "1/2", reference: "https://www.dndbeyond.com/monsters/Ice-Mephit" },
  { xp: 200, type: "Imp", hpRoll: _roll(3, DiceType.d4), hpModifier: 3, challenge: "1", reference: "https://www.dndbeyond.com/monsters/Imp" },
  { xp: 2300, type: "Invisible Stalker", hpRoll: _roll(16, DiceType.d8), hpModifier: 32, challenge: "6", reference: "https://www.dndbeyond.com/monsters/Invisible-Stalker" },
  { xp: 15000, type: "Iron Golem", hpRoll: _roll(20, DiceType.d10), hpModifier: 100, challenge: "16", reference: "https://www.dndbeyond.com/monsters/Iron-Golem" },
  { xp: 10, type: "Jackal", hpRoll: _roll(1, DiceType.d6), hpModifier: 0, challenge: "0", reference: "https://www.dndbeyond.com/monsters/Jackal" },
  { xp: 700, type: "Killer Whale", hpRoll: _roll(12, DiceType.d12), hpModifier: 12, challenge: "3", reference: "https://www.dndbeyond.com/monsters/Killer-Whale" },
  { xp: 25, type: "Kobold", hpRoll: _roll(2, DiceType.d6), hpModifier: 0, challenge: "1/8", reference: "https://www.dndbeyond.com/monsters/Kobold" },
  { xp: 50000, type: "Kraken", hpRoll: _roll(27, DiceType.d20), hpModifier: 189, challenge: "23", reference: "https://www.dndbeyond.com/monsters/Kraken" },
  { xp: 1100, type: "Lamia", hpRoll: _roll(13, DiceType.d10), hpModifier: 26, challenge: "4", reference: "https://www.dndbeyond.com/monsters/Lamia" },
  { xp: 10, type: "Lemure", hpRoll: _roll(3, DiceType.d8), hpModifier: 0, challenge: "0", reference: "https://www.dndbeyond.com/monsters/Lemure" },
  { xp: 33000, type: "Lich", hpRoll: _roll(18, DiceType.d8), hpModifier: 54, challenge: "21", reference: "https://www.dndbeyond.com/monsters/Lich" },
  { xp: 200, type: "Lion", hpRoll: _roll(4, DiceType.d10), hpModifier: 4, challenge: "1", reference: "https://www.dndbeyond.com/monsters/Lion" },
  { xp: 10, type: "Lizard", hpRoll: _roll(1, DiceType.d4), hpModifier: 0, challenge: "0", reference: "https://www.dndbeyond.com/monsters/Lizard" },
  { xp: 100, type: "Lizardfolk", hpRoll: _roll(4, DiceType.d8), hpModifier: 4, challenge: "1/2", reference: "https://www.dndbeyond.com/monsters/Lizardfolk" },
  { xp: 100, type: "Magma Mephit", hpRoll: _roll(5, DiceType.d6), hpModifier: 5, challenge: "1/2", reference: "https://www.dndbeyond.com/monsters/Magma-Mephit" },
  { xp: 2300, type: "Magmin", hpRoll: _roll(2, DiceType.d6), hpModifier: 2, challenge: "1/2", reference: "https://www.dndbeyond.com/monsters/Magmin" },
  { xp: 700, type: "Mammoth", hpRoll: _roll(11, DiceType.d12), hpModifier: 55, challenge: "6", reference: "https://www.dndbeyond.com/monsters/Mammoth" },
  { xp: 100, type: "Manticore", hpRoll: _roll(8, DiceType.d10), hpModifier: 24, challenge: "3", reference: "https://www.dndbeyond.com/monsters/Manticore" },
  { xp: 15000, type: "Marilith", hpRoll: _roll(18, DiceType.d10), hpModifier: 90, challenge: "16", reference: "https://www.dndbeyond.com/monsters/Marilith" },
  { xp: 25, type: "Mastiff", hpRoll: _roll(1, DiceType.d8), hpModifier: 1, challenge: "1/8", reference: "https://www.dndbeyond.com/monsters/Mastiff" },
  { xp: 2300, type: "Medusa", hpRoll: _roll(17, DiceType.d8), hpModifier: 51, challenge: "6", reference: "https://www.dndbeyond.com/monsters/Medusa" },
  { xp: 25, type: "Merfolk", hpRoll: _roll(2, DiceType.d8), hpModifier: 2, challenge: "1/8", reference: "https://www.dndbeyond.com/monsters/Merfolk" },
  { xp: 450, type: "Merrow", hpRoll: _roll(6, DiceType.d10), hpModifier: 12, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Merrow" },
  { xp: 450, type: "Mimic", hpRoll: _roll(9, DiceType.d8), hpModifier: 18, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Mimic" },
  { xp: 700, type: "Minotaur", hpRoll: _roll(9, DiceType.d10), hpModifier: 27, challenge: "3", reference: "https://www.dndbeyond.com/monsters/Minotaur" },
  { xp: 25, type: "Minotaur Skeleton", hpRoll: _roll(9, DiceType.d10), hpModifier: 18, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Minotaur-Skeleton" },
  { xp: 450, type: "Mule", hpRoll: _roll(2, DiceType.d8), hpModifier: 2, challenge: "1/8", reference: "https://www.dndbeyond.com/monsters/Mule" },
  { xp: 700, type: "Mummy", hpRoll: _roll(9, DiceType.d8), hpModifier: 18, challenge: "3", reference: "https://www.dndbeyond.com/monsters/Mummy" },
  { xp: 13000, type: "Mummy Lord", hpRoll: _roll(13, DiceType.d8), hpModifier: 39, challenge: "15", reference: "https://www.dndbeyond.com/monsters/Mummy-Lord" },
  { xp: 10000, type: "Nalfeshnee", hpRoll: _roll(16, DiceType.d10), hpModifier: 96, challenge: "", reference: "https://www.dndbeyond.com/monsters/Nalfeshnee" },
  { xp: 700, type: "Nightmare", hpRoll: _roll(8, DiceType.d10), hpModifier: 24, challenge: "", reference: "https://www.dndbeyond.com/monsters/Nightmare" },
  { xp: 1800, type: "Night Hag", hpRoll: _roll(15, DiceType.d8), hpModifier: 45, challenge: "", reference: "https://www.dndbeyond.com/monsters/Night-Hag" },
  { xp: 450, type: "Nothic", hpRoll: _roll(6, DiceType.d8), hpModifier: 18, challenge: "", reference: "https://www.dndbeyond.com/monsters/Nothic" },
  { xp: 450, type: "Ochre Jelly", hpRoll: _roll(6, DiceType.d10), hpModifier: 12, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Ochre-Jelly" },
  { xp: 10, type: "Octopus", hpRoll: _roll(1, DiceType.d6), hpModifier: 0, challenge: "0", reference: "https://www.dndbeyond.com/monsters/Octopus" },
  { xp: 450, type: "Ogre", hpRoll: _roll(7, DiceType.d10), hpModifier: 21, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Ogre" },
  { xp: 450, type: "Ogre Zombie", hpRoll: _roll(9, DiceType.d10), hpModifier: 36, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Ogre-Zombie" },
  { xp: 2900, type: "Oni", hpRoll: _roll(13, DiceType.d10), hpModifier: 39, challenge: "7", reference: "https://www.dndbeyond.com/monsters/Oni" },
  { xp: 100, type: "Orc", hpRoll: _roll(2, DiceType.d8), hpModifier: 6, challenge: "1/2", reference: "https://www.dndbeyond.com/monsters/Orc" },
  { xp: 1800, type: "Otyugh", hpRoll: _roll(12, DiceType.d10), hpModifier: 48, challenge: "5", reference: "https://www.dndbeyond.com/monsters/Otyugh" },
  { xp: 10, type: "Owl", hpRoll: _roll(1, DiceType.d4), hpModifier: 0, challenge: "0", reference: "https://www.dndbeyond.com/monsters/Owl" },
  { xp: 700, type: "Owlbear", hpRoll: _roll(7, DiceType.d10), hpModifier: 21, challenge: "3", reference: "https://www.dndbeyond.com/monsters/Owlbear" },
  { xp: 50, type: "Panther", hpRoll: _roll(3, DiceType.d8), hpModifier: 0, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Panther" },
  { xp: 450, type: "Pegasus", hpRoll: _roll(7, DiceType.d10), hpModifier: 21, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Pegasus" },
  { xp: 700, type: "Phase Spider", hpRoll: _roll(5, DiceType.d10), hpModifier: 5, challenge: "3", reference: "https://www.dndbeyond.com/monsters/Phase-Spider" },
  { xp: 25000, type: "Pit Fiend", hpRoll: _roll(24, DiceType.d10), hpModifier: 168, challenge: "20", reference: "https://www.dndbeyond.com/monsters/Pit-Fiend" },
  { xp: 15000, type: "Planetar", hpRoll: _roll(16, DiceType.d10), hpModifier: 112, challenge: "16", reference: "https://www.dndbeyond.com/monsters/Planetar" },
  { xp: 450, type: "Plesiosaurus", hpRoll: _roll(8, DiceType.d10), hpModifier: 24, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Plesiosaurus" },
  { xp: 25, type: "Poisonous Snake", hpRoll: _roll(1, DiceType.d4), hpModifier: 0, challenge: "1/8", reference: "https://www.dndbeyond.com/monsters/Poisonous-Snake" },
  { xp: 450, type: "Polar Bear", hpRoll: _roll(5, DiceType.d10), hpModifier: 15, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Polar-Bear" },
  { xp: 25, type: "Pony", hpRoll: _roll(2, DiceType.d8), hpModifier: 2, challenge: "1/8", reference: "https://www.dndbeyond.com/monsters/Pony" },
  { xp: 50, type: "Pseudodragon", hpRoll: _roll(2, DiceType.d4), hpModifier: 2, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Pseudodragon" },
  { xp: 50, type: "Pteranodon", hpRoll: _roll(3, DiceType.d8), hpModifier: 0, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Pteranodon" },
  { xp: 13000, type: "Purple Worm", hpRoll: _roll(15, DiceType.d20), hpModifier: 90, challenge: "15", reference: "https://www.dndbeyond.com/monsters/Purple-Worm" },
  { xp: 200, type: "Quasit", hpRoll: _roll(3, DiceType.d4), hpModifier: 0, challenge: "1", reference: "https://www.dndbeyond.com/monsters/Quasit" },
  { xp: 10, type: "Quipper", hpRoll: _roll(1, DiceType.d4), hpModifier: 0, challenge: "0", reference: "https://www.dndbeyond.com/monsters/Quipper" },
  { xp: 10000, type: "Rakshasa", hpRoll: _roll(13, DiceType.d8), hpModifier: 52, challenge: "", reference: "https://www.dndbeyond.com/monsters/Rakshasa" },
  { xp: 10, type: "Rat", hpRoll: _roll(1, DiceType.d4), hpModifier: 0, challenge: "0", reference: "https://www.dndbeyond.com/monsters/Rat" },
  { xp: 10, type: "Raven", hpRoll: _roll(1, DiceType.d4), hpModifier: 0, challenge: "0", reference: "https://www.dndbeyond.com/monsters/Raven" },
  { xp: 1100, type: "Red Dragon Wyrmling", hpRoll: _roll(10, DiceType.d8), hpModifier: 30, challenge: "4", reference: "https://www.dndbeyond.com/monsters/Red-Dragon-Wyrmling" },
  { xp: 100, type: "Reef Shark", hpRoll: _roll(4, DiceType.d8), hpModifier: 4, challenge: "1/2", reference: "https://www.dndbeyond.com/monsters/Reef-Shark" },
  { xp: 7200, type: "Remorhaz", hpRoll: _roll(17, DiceType.d12), hpModifier: 85, challenge: "", reference: "https://www.dndbeyond.com/monsters/Remorhaz" },
  { xp: 450, type: "Rhinoceros", hpRoll: _roll(6, DiceType.d10), hpModifier: 12, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Rhinoceros" },
  { xp: 50, type: "Riding Horse", hpRoll: _roll(2, DiceType.d10), hpModifier: 2, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Riding-Horse" },
  { xp: 7200, type: "Roc", hpRoll: _roll(16, DiceType.d20), hpModifier: 80, challenge: "", reference: "https://www.dndbeyond.com/monsters/Roc" },
  { xp: 1800, type: "Roper", hpRoll: _roll(11, DiceType.d10), hpModifier: 33, challenge: "", reference: "https://www.dndbeyond.com/monsters/Roper" },
  { xp: 100, type: "Rug of Smothering", hpRoll: _roll(6, DiceType.d10), hpModifier: 0, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Rug-of-Smothering" },
  { xp: 450, type: "Rust Monster", hpRoll: _roll(5, DiceType.d8), hpModifier: 5, challenge: "", reference: "https://www.dndbeyond.com/monsters/Rust-Monster" },
  { xp: 450, type: "Saber-Toothed Tiger", hpRoll: _roll(7, DiceType.d10), hpModifier: 14, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Saber-Toothed-Tiger" },
  { xp: 100, type: "Sahuagin", hpRoll: _roll(4, DiceType.d8), hpModifier: 4, challenge: "1/2", reference: "https://www.dndbeyond.com/monsters/Sahuagin" },
  { xp: 1800, type: "Salamander", hpRoll: _roll(12, DiceType.d10), hpModifier: 24, challenge: "5", reference: "https://www.dndbeyond.com/monsters/Salamander" },
  { xp: 100, type: "Satyr", hpRoll: _roll(7, DiceType.d8), hpModifier: 0, challenge: "1/2", reference: "https://www.dndbeyond.com/monsters/Satyr" },
  { xp: 10, type: "Scorpion", hpRoll: _roll(1, DiceType.d4), hpModifier: 0, challenge: "0", reference: "https://www.dndbeyond.com/monsters/Scorpion" },
  { xp: 450, type: "Sea Hag", hpRoll: _roll(7, DiceType.d8), hpModifier: 21, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Sea-Hag" },
  { xp: 10, type: "Sea Horse", hpRoll: _roll(1, DiceType.d4), hpModifier: 0, challenge: "", reference: "https://www.dndbeyond.com/monsters/Sea-Horse" },
  { xp: 100, type: "Shadow", hpRoll: _roll(3, DiceType.d8), hpModifier: 3, challenge: "1/2", reference: "https://www.dndbeyond.com/monsters/Shadow" },
  { xp: 1800, type: "Shambling Mound", hpRoll: _roll(16, DiceType.d10), hpModifier: 48, challenge: "5", reference: "https://www.dndbeyond.com/monsters/Shambling-Mound" },
  { xp: 2900, type: "Shield Guardian", hpRoll: _roll(15, DiceType.d10), hpModifier: 60, challenge: "7", reference: "https://www.dndbeyond.com/monsters/Shield-Guardian" },
  { xp: 10, type: "Shrieker", hpRoll: _roll(3, DiceType.d8), hpModifier: 0, challenge: "0", reference: "https://www.dndbeyond.com/monsters/Shrieker" },
  { xp: 450, type: "Silver Dragon Wyrmling", hpRoll: _roll(6, DiceType.d8), hpModifier: 18, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Silver-Dragon-Wyrmling" },
  { xp: 50, type: "Skeleton", hpRoll: _roll(2, DiceType.d8), hpModifier: 4, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Skeleton" },
  { xp: 33000, type: "Solar", hpRoll: _roll(18, DiceType.d10), hpModifier: 144, challenge: "21", reference: "https://www.dndbeyond.com/monsters/Solar" },
  { xp: 700, type: "Spectator", hpRoll: _roll(6, DiceType.d8), hpModifier: 12, challenge: "3", reference: "https://www.dndbeyond.com/monsters/Spectator" },
  { xp: 200, type: "Specter", hpRoll: _roll(5, DiceType.d8), hpModifier: 0, challenge: "1", reference: "https://www.dndbeyond.com/monsters/Specter" },
  { xp: 10, type: "Spider", hpRoll: _roll(1, DiceType.d4), hpModifier: 0, challenge: "0", reference: "https://www.dndbeyond.com/monsters/Spider" },
  { xp: 3900, type: "Spirit Naga", hpRoll: _roll(10, DiceType.d10), hpModifier: 20, challenge: "8", reference: "https://www.dndbeyond.com/monsters/Spirit-Naga" },
  { xp: 50, type: "Sprite", hpRoll: _roll(1, DiceType.d4), hpModifier: 0, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Sprite" },
  { xp: 50, type: "Steam Mephit", hpRoll: _roll(6, DiceType.d6), hpModifier: 0, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Steam-Mephit" },
  { xp: 2900, type: "Stirge", hpRoll: _roll(1, DiceType.d4), hpModifier: 0, challenge: "1/8", reference: "https://www.dndbeyond.com/monsters/Stirge" },
  { xp: 25, type: "Stone Giant", hpRoll: _roll(11, DiceType.d12), hpModifier: 55, challenge: "7", reference: "https://www.dndbeyond.com/monsters/Stone-Giant" },
  { xp: 5900, type: "Stone Golem", hpRoll: _roll(17, DiceType.d10), hpModifier: 85, challenge: "10", reference: "https://www.dndbeyond.com/monsters/Stone-Golem" },
  { xp: 10000, type: "Storm Giant", hpRoll: _roll(20, DiceType.d12), hpModifier: 100, challenge: "13", reference: "https://www.dndbeyond.com/monsters/Storm-Giant" },
  { xp: 1100, type: "Succubus/Incubus", hpRoll: _roll(12, DiceType.d8), hpModifier: 12, challenge: "4", reference: "https://www.dndbeyond.com/monsters/Succubus" },
  { xp: 50, type: "Swarm of Bats", hpRoll: _roll(5, DiceType.d8), hpModifier: 0, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Swarm-of-Bats" },
  { xp: 100, type: "Swarm of Insects", hpRoll: _roll(5, DiceType.d8), hpModifier: 0, challenge: "1/2", reference: "https://www.dndbeyond.com/monsters/Swarm-of-Insects" },
  { xp: 450, type: "Swarm of Poisonous Snakes", hpRoll: _roll(8, DiceType.d8), hpModifier: 0, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Swarm-of-Poisonous-Snakes" },
  { xp: 200, type: "Swarm of Quippers", hpRoll: _roll(8, DiceType.d8), hpModifier: 0, challenge: "1", reference: "https://www.dndbeyond.com/monsters/Swarm-of-Quippers" },
  { xp: 50, type: "Swarm of Rats", hpRoll: _roll(7, DiceType.d8), hpModifier: 0, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Swarm-of-Rats" },
  { xp: 50, type: "Swarm of Ravens", hpRoll: _roll(7, DiceType.d8), hpModifier: 0, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Swarm-of-Ravens" },
  { xp: 155000, type: "Tarrasque", hpRoll: _roll(33, DiceType.d20), hpModifier: 330, challenge: "30", reference: "https://www.dndbeyond.com/monsters/Tarrasque" },
  { xp: 200, type: "Tiger", hpRoll: _roll(5, DiceType.d10), hpModifier: 10, challenge: "1", reference: "https://www.dndbeyond.com/monsters/Tiger" },
  { xp: 5000, type: "Treant", hpRoll: _roll(12, DiceType.d12), hpModifier: 60, challenge: "9", reference: "https://www.dndbeyond.com/monsters/Treant" },
  { xp: 1800, type: "Triceratops", hpRoll: _roll(10, DiceType.d12), hpModifier: 30, challenge: "5", reference: "https://www.dndbeyond.com/monsters/Triceratops" },
  { xp: 1800, type: "Troll", hpRoll: _roll(8, DiceType.d10), hpModifier: 40, challenge: "", reference: "https://www.dndbeyond.com/monsters/Troll" },
  { xp: 25, type: "Twig Blight", hpRoll: _roll(1, DiceType.d6), hpModifier: 1, challenge: "1/8", reference: "https://www.dndbeyond.com/monsters/Twig-Blight" },
  { xp: 3900, type: "Tyrannosaurus Rex", hpRoll: _roll(13, DiceType.d12), hpModifier: 52, challenge: "8", reference: "https://www.dndbeyond.com/monsters/Tyrannosaurus-Rex" },
  { xp: 1800, type: "Unicorn", hpRoll: _roll(9, DiceType.d10), hpModifier: 18, challenge: "5", reference: "https://www.dndbeyond.com/monsters/Unicorn" },
  { xp: 10000, type: "Vampire", hpRoll: _roll(17, DiceType.d8), hpModifier: 68, challenge: "13", reference: "https://www.dndbeyond.com/monsters/Vampire" },
  { xp: 1800, type: "Vampire Spawn", hpRoll: _roll(11, DiceType.d8), hpModifier: 33, challenge: "5", reference: "https://www.dndbeyond.com/monsters/Vampire-Spawn" },
  { xp: 50, type: "Violet Fungus", hpRoll: _roll(4, DiceType.d8), hpModifier: 0, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Violet-Fungus" },
  { xp: 2300, type: "Vrock", hpRoll: _roll(11, DiceType.d10), hpModifier: 44, challenge: "6", reference: "https://www.dndbeyond.com/monsters/Vrock" },
  { xp: 10, type: "Vulture", hpRoll: _roll(1, DiceType.d8), hpModifier: 1, challenge: "0", reference: "https://www.dndbeyond.com/monsters/Vulture" },
  { xp: 100, type: "Warhorse", hpRoll: _roll(3, DiceType.d10), hpModifier: 3, challenge: "1/2", reference: "https://www.dndbeyond.com/monsters/Warhorse" },
  { xp: 100, type: "Warhorse Skeleton", hpRoll: _roll(3, DiceType.d10), hpModifier: 6, challenge: "1/2", reference: "https://www.dndbeyond.com/monsters/Warhorse-Skeleton" },
  { xp: 1800, type: "Water Elemental", hpRoll: _roll(12, DiceType.d10), hpModifier: 48, challenge: "5", reference: "https://www.dndbeyond.com/monsters/Water-Elemental" },
  { xp: 10, type: "Weasel", hpRoll: _roll(1, DiceType.d4), hpModifier: 0, challenge: "0", reference: "https://www.dndbeyond.com/monsters/Weasel" },
  { xp: 1800, type: "Werebear", hpRoll: _roll(18, DiceType.d8), hpModifier: 54, challenge: "5", reference: "https://www.dndbeyond.com/monsters/Werebear" },
  { xp: 1100, type: "Wereboar", hpRoll: _roll(12, DiceType.d8), hpModifier: 24, challenge: "4", reference: "https://www.dndbeyond.com/monsters/Wereboar" },
  { xp: 450, type: "Wererat", hpRoll: _roll(6, DiceType.d8), hpModifier: 6, challenge: "2", reference: "https://www.dndbeyond.com/monsters/Wererat" },
  { xp: 1100, type: "Weretiger", hpRoll: _roll(16, DiceType.d8), hpModifier: 48, challenge: "4", reference: "https://www.dndbeyond.com/monsters/Weretiger" },
  { xp: 700, type: "Werewolf", hpRoll: _roll(9, DiceType.d8), hpModifier: 18, challenge: "3", reference: "https://www.dndbeyond.com/monsters/Werewolf" },
  { xp: 450, type: "White Dragon Wyrmling", hpRoll: _roll(5, DiceType.d8), hpModifier: 10, challenge: "2", reference: "https://www.dndbeyond.com/monsters/White-Dragon-Wyrmling" },
  { xp: 700, type: "Wight", hpRoll: _roll(6, DiceType.d8), hpModifier: 18, challenge: "", reference: "https://www.dndbeyond.com/monsters/Wight" },
  { xp: 450, type: "Will-o’-Wisp", hpRoll: _roll(9, DiceType.d4), hpModifier: 0, challenge: "", reference: "https://www.dndbeyond.com/monsters/Will-o-Wisp" },
  { xp: 700, type: "Winter Wolf", hpRoll: _roll(10, DiceType.d10), hpModifier: 20, challenge: "3", reference: "https://www.dndbeyond.com/monsters/Winter-Wolf" },
  { xp: 50, type: "Wolf", hpRoll: _roll(2, DiceType.d8), hpModifier: 2, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Wolf" },
  { xp: 100, type: "Worg", hpRoll: _roll(4, DiceType.d10), hpModifier: 4, challenge: "1/2", reference: "https://www.dndbeyond.com/monsters/Worg" },
  { xp: 1800, type: "Wraith", hpRoll: _roll(9, DiceType.d8), hpModifier: 27, challenge: "", reference: "https://www.dndbeyond.com/monsters/Wraith" },
  { xp: 2300, type: "Wyvern", hpRoll: _roll(13, DiceType.d10), hpModifier: 39, challenge: "", reference: "https://www.dndbeyond.com/monsters/Wyvern" },
  { xp: 1800, type: "Xorn", hpRoll: _roll(7, DiceType.d8), hpModifier: 42, challenge: "5", reference: "https://www.dndbeyond.com/monsters/Xorn" },
  { xp: 5, type: "Zombie", hpRoll: _roll(3, DiceType.d8), hpModifier: 9, challenge: "1/4", reference: "https://www.dndbeyond.com/monsters/Zombie" },

  //CoS specific
  { xp: 450, type: "Wereraven", hpRoll: _roll(7, DiceType.d8), challenge: "2", hpModifier: 0, reference: "https://dnd-5e.herokuapp.com/monsters/wereraven" },
  { xp: 50, type: "Needdle Blight", hpRoll: _roll(2, DiceType.d8), challenge: "1/4", hpModifier: 2, reference: "https://dnd-5e.herokuapp.com/monsters/needle-blight" },
  { xp: 1800, type: "Revenant", hpRoll: _roll(16, DiceType.d8), challenge: "5", hpModifier: 64, reference: "https://dnd-5e.herokuapp.com/monsters/revenant" },
  { xp: 200, type: "Scarecrow", hpRoll: _roll(8, DiceType.d8), challenge: "1", hpModifier: 0, reference: "https://dnd-5e.herokuapp.com/monsters/scarecrow" },
  { xp: 200, type: "Strahd's Zombie", hpRoll: _roll(4, DiceType.d8), challenge: "1", hpModifier: 12, reference: "https://dnd-5e.herokuapp.com/monsters/strahd-zombie" },
  { xp: 3900, type: "Esmerelda d’Avenir", hpRoll: _roll(11, DiceType.d8), challenge: "8", hpModifier: 33, reference: "https://dnd-5e.herokuapp.com/monsters/esmerelda-davenir" },
  { xp: 5900, type: "Rahadin", hpRoll: _roll(18, DiceType.d8), challenge: "10", hpModifier: 54, reference: "https://dnd-5e.herokuapp.com/monsters/rahadin" },
  { xp: 50, type: "Broom of Animated Attack", hpRoll: _roll(5, DiceType.d6), challenge: "1/4", hpModifier: 0, reference: "https://dnd-5e.herokuapp.com/monsters/broom-of-animated-attack" },
  { xp: 10, type: "Crawling Claw", hpRoll: _roll(1, DiceType.d4), challenge: "0", hpModifier: 0, reference: "https://dnd-5e.herokuapp.com/monsters/crawling-claw" },
  { xp: 100, type: "Barovian Witch", hpRoll: _roll(3, DiceType.d8), challenge: "1/2", hpModifier: 3, reference: "https://dnd-5e.herokuapp.com/monsters/barovian-witch" },
  { xp: 3000, type: "Strahd", hpRoll: _roll(17, DiceType.d8), challenge: "15", hpModifier: 68, reference: "https://dnd-5e.herokuapp.com/monsters/strahd-von-zarovich" },
];

export const getMonsterDataFor = (type: MonsterType | IMonsterData): IMonsterData => {
  const monster = ((type as IMonsterData).xp === undefined ? monsterData.find(m => m.type === type) : type) as IMonsterData;
  monster.hp = monster.hpRoll!() + monster.hpModifier!;

  return monster;
}